#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mNombre Del Nuevo Usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mContraseña Del Nuevo Usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mCuantos Dias La Cuenta $name Debe Durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mLimite De Logins Simultaneos:\033[0;37m"; read -p " " limiteuser
	echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name Ya Existe\033[0m"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		( echo "$pass";echo "$pass" ) | passwd $name 2> /dev/null
		limite $name $limiteuser
		echo -e "\033[1;36mUsuario: \033[0m$name"
		echo -e "\033[1;36mContraseña: \033[0m$pass"
		echo -e "\033[1;36mExpira:\033[0m $datexp"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Su Usuario Esta En El Grupo root"
	echo -e "Para Para Cambiar Teclee \033[1;31msudo su\033[0m"
	echo -e "O Ejecute crearusuario Como root. \033[1;31msudo crearusuario\033[0m"
	else
	echo -e "Usted Ya Esta Como Usuario root No Necesita (sudo)\nPara Ejecutar Como root \033[1;31msu\033[0m y Digite Su Contraseña root"
	fi
fi
