#!/bin/bash
clear
echo -e "\033[1;33mOpciones:\033[1;30m
1) Eliminar Usuario
2) Eliminar y Desconectar TOdos Del Usuario
3) Desconectar Todos Del Usuario\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Nombre Del Usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario No Existe"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuario $name Fue Eliminado"
 exit
 fi

 if [ $option -eq 2 ]; then
 read -p "Nombre Del Usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario No Existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "Usuario $name Sera Eliminado"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Nombre Del Usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario No Existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "Usuario $name Fue Eliminado"
 exit
 fi
