#!/bin/bash
read -p "Nombre Del Usuario: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer No Existe"
 exit
 fi
clear
echo -e "\033[1;33mOpciones A Modificar ?\033[1;30m
1) Numero De Logins
2) Fecha De Expiracion
3) Cambiar Contraseña Del Usuario"
read -p "Opcion: " option
if [ $option -eq 1 ]; then
read -p "Cual Es El Nuevo Numero De Logins: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Cual Es La Nueva Fecha : Formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Fecha: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Cual Es La Nueva Contraseña Para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nueva Contraseña Aplicada"
exit
fi
